swagger: "2.0"

info:
  version: 0.1.0
  title: API

basePath: /api/v1

paths:
  /uploads:
    get:
      description: Get the list of CPLs and their upload statuses
      parameters:
        - name: "cpl-id"
          in : "query"
          type: string
          description: Unique id of the cpl. can be added multiple times
        - name: "status"
          in: "query"
          description: If this value is true then all past uploads are listed as well
          type: string
          enum: [uploading, verifying, verified, cancelled, failed, completed, incomplete, expired]
      responses:
        "200":
          description: Upload CPLs
          schema:
            type: object
            properties:
              cpls:
                type: array
                items:
                  enum: [value1]
      tags:
        - Uploads 
