name: Validate

on: push

jobs:
    validate:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -   uses: mbowman100/swagger-validator-action@master
                with:
                    files: |
                        swagger/valid.yml
            -   uses: mbowman100/swagger-validator-action@master
                with:
                    files: |
                        swagger/invalid.yml
            -   name: swagger-cli
                uses: vaibhav-jain/spectral-action/@v2.6
                with:
                    file_path: swagger/valid.yml
            -   name: swagger-cli
                uses: vaibhav-jain/spectral-action/@v2.6
                with:
                    file_path: swagger/invalid.yml