name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: >
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}
                    
            -   name: CI fail
                run: |
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}
                    
            -   name: CI fail
                run: >-
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}
                    
            -   name: CI fail
                run: |-
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}

            -   name: CI fail
                run: >+
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}
                    
            -   name: CI fail
                run: |+
                    echo ${{ format('{0}\n{1}', 'line1', 'line2') }}
