name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat') }}

            -   name: CI fail
                run: echo ${{ format('Hello \n {0} {1} {2}', 'Mona', 'the', 'Octocat') }}

            -   name: CI fail
                run: >
                    echo ${{ format('Hello {0} \n {1} {2}', 'Mona', 'the', 'Octocat') }}
