name: Build

on:
  push:
    paths:
    - 'test/**'

jobs:
    build1:
        name: Build1
        runs-on: ubuntu-latest
        steps:
            -   name: echo
                run: echo build1

    build2:
        name: Build2
        needs: build1
        runs-on: ubuntu-latest
        steps:
            -   name: echo
                run: echo build2