name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: >
                    echo ${{ 
                        format('{{"text": "{0}"}}', 
                            format('Commit: {0}/commit/{1}\nBranch: {2}\nRepository: {0}\nWorkflow URL: {0}/actions/runs/{3}', 
                                format('https://github.com/{0}', github.repository), 
                                github.sha, 
                                github.ref, 
                                github.run_id
                            )
                        ) 
                    }}
