name: Build

on:
  push:
    # paths:
    # - 'test/**'

jobs:
    build1:
        name: Build1
        runs-on: ubuntu-latest
        steps:
            -   name: echo
                run: echo build1

    build2:
        name: Build2
        needs: build1
        runs-on: ubuntu-latest
        steps:
            -   name: echo
                run: echo build2

    hello_world_job:
        runs-on: ubuntu-latest
        name: A job to say hello
        steps:
            -   uses: actions/checkout@v2
            -   id: foo
                uses: ashwinspg/explore-github-actions@0d93d20a9aad01b70ac328fd2705ad0b2723c936
                with:
                    who-to-greet: 'Mona the Octocat'
            -   run: echo random-number ${{ steps.foo.outputs.random-number }} 
                shell: bash