name: Build

on: push

jobs:
    build1:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Go 1.14
                uses: actions/setup-go@v2
                with:
                    go-version: ^1.14

            -   name: Echo
                run: go env

    build2:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: Set up Go 1.15
                uses: actions/setup-go@v2
                with:
                    go-version: ^1.15

            -   name: Echo
                run: go env
