name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                lambda-function:
                    -   id: 'movies-lambda'
                        path: 'movies-lambda'
                        template-file-path: 'movies-lambda'
                    -   id: 'movies-sync-lambda'
                        path: 'movies-lambda/sync'
                        template-file-path: 'movies-lambda'
        steps:
            -   name: echo
                run: |
                    echo -e "\npre"
                    echo ${{ matrix.path }}
                    echo -e "\npost"


    # hello_world_job:
    #     runs-on: ubuntu-latest
    #     name: A job to say hello
    #     defaults:
    #         run:
    #             working-directory: test
    #     steps:
    #         -   uses: actions/checkout@v2
    #         -   name: echo
    #             run: echo ${{ github.workspace }}
    #         -   id: foo
    #             uses: ashwinspg/explore-github-actions@master
    #             with:
    #                 who-to-greet: 'Mona the Octocat'
    #                 path: ./test                    
    #         -   run: echo random-number ${{ steps.foo.outputs.random-number }} 
    #             shell: bash