name: Build

on:
  push:
    paths:
    - 'test/*'

jobs:
    build1:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: echo build1

    build2:
        name: Build
        needs: build1
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: echo build2