name: Validate

on: push

jobs:
    validate:
        name: Validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -   uses: mbowman100/swagger-validator-action@master
                with:
                    files: |
                        swagger/valid.yml
            -   uses: mbowman100/swagger-validator-action@master
                with:
                    files: |
                        swagger/invalid.yml
            -   name: Validate OpenAPI definition
                uses: char0n/swagger-editor-validate@v1
                with:
                    definition-file: swagger/valid.yml
            -   name: Validate OpenAPI definition
                uses: char0n/swagger-editor-validate@v1
                with:
                    definition-file: swagger/invalid.yml