name: Build

on: push

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            -   name: CI fail
                run: | 
                    format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')
                    format('Hello \n {0} {1} {2}', 'Mona', 'the', 'Octocat')
                    format('Hello {0} {1} {2}', 'Mona', 'the', 'Octocat')
